name = "EnergyScheduling"
uuid = "c606f401-43a9-482c-85f9-6793b2e664a8"
authors = ["jorgelfer <jorgeferram17@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
